apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 730335535410.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 730335535410.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e4c89e1b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
